authors = ["TuneScotty"]
name = "tunescotty/datum_serde"
version = "0.1.6"
description = "Type-safe data serialization, migration, and versioning for Roblox"
license = "MIT"
repository = "https://github.com/TuneScotty/datum-serde"

includes = [
    "README.md",
    "LICENSE",
    "pesde.toml",
    "src/**/*",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src", "src/codec"]

[indices]
default = "https://github.com/pesde-pkg/index"