[package]
name = "tunescotty/datum-serde"
version = "0.1.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "Type-safe data serialization, migration, and versioning for Roblox"
license = "MIT"
authors = ["TuneScotty"]